Update test

diff --git a/test b/test
--- a/test
+++ b/test
@@ -1,135 +1,73 @@
-#include "highlight-overlay-manager.h"
+#!/bin/bash
 
-#include <dali/public-api/actors/actor.h>
-#include <dali/public-api/math/vector2.h>
-#include <dali/public-api/math/rect.h>
-#include <dali/public-api/common/constants.h>
-#include <dali-scene3d/public-api/controls/scene-view/scene-view.h>
-#include <dali/devel-api/common/owner-container.h>
 
-namespace Dali::Toolkit::DevelControl
+TEMP=`getopt -o rn --long rebuild,no-gen \
+     -n 'genmake' -- "$@"`
+
+if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
+
+# Note the quotes around `$TEMP': they are essential!
+eval set -- "$TEMP"
+
+opt_rebuild=false
+opt_generate=true
+
+while true ; do
+    case "$1" in
+        -r|--rebuild) opt_rebuild=true ; shift ;;
+        -n|--no-gen)  opt_generate=false ; shift ;;
+        --) shift ; break ;;
+        *) shift ;;   # Ignore
+    esac
+done
+
+if [ false == $opt_rebuild -o ! -d "build" ] ; then
+    rm -rf build
+    mkdir build
+fi
+
+function build
 {
-
-HighlightOverlayManager::HighlightOverlayManager()
-: mOverlayMode(OverlayHighlightMode::Auto),
-  mManualPosition(0.0f, 0.0f),
-  mManualSize(0.0f, 0.0f)
-{
+    if [ $opt_generate == true -o $opt_rebuild == false ] ; then
+        (cd src/$1; ../../scripts/tcheadgen.sh tct-$1-core.h)
+        if [ $? -ne 0 ]; then echo "Aborting..."; exit 1; fi
+    fi
+    BUILDSYSTEM="Unix Makefiles"
+    BUILDCMD=make
+    if [ -e ../build/tizen/build.ninja ] ; then
+        BUILDSYSTEM="Ninja"
+        BUILDCMD=ninja
+    fi
+    CACHE_CPP='/usr/lib/ccache/g++' CACHE_CC='/usr/lib/ccache/gcc'
+    if [ -e $CACHE_CPP ] ; then
+        (cd build ; CXX=$CACHE_CPP CC=$CACHE_CC cmake .. -DMODULE=$1 -G "$BUILDSYSTEM" ; $BUILDCMD -j7 )
+    else
+        (cd build ; cmake .. -DMODULE=$1 -G "$BUILDSYSTEM" ; $BUILDCMD -j7 )
+    fi
 }
 
-void HighlightOverlayManager::SetCustomHighlight(Vector2 position, Vector2 size)
-{
-  mManualPosition = position;
-  mManualSize     = size;
-  mOverlayMode    = OverlayHighlightMode::Manual;
-}
+# Query main build to determine if we are enabling USD loader
+USD_LOADER_ENABLED=0
+(cd ../build/tizen ; cmake -LA -N 2>/dev/null | grep USD_LOADER_ENABLED | grep "\=ON")
+if [ $? -eq 0 ] ; then
+    USD_LOADER_ENABLED=1
+fi
 
-void HighlightOverlayManager::ResetCustomHighlight()
-{
-  mOverlayMode = OverlayHighlightMode::Auto;
-}
+if [ -n "$1" ] ; then
+  echo BUILDING ONLY $1
+  build $1
+else
+  for mod in `ls -1 src/ | grep -v CMakeList `
+  do
+    if [ $mod != 'common' ] && [ $mod != 'manual' ]; then
+        if [ $mod != 'dali-usd-loader' ] || [[ $mod == 'dali-usd-loader' && $USD_LOADER_ENABLED == 1 ]]; then
+            echo BUILDING $mod
+            build $mod
+            if [ $? -ne 0 ]; then echo "Build failed" ; exit 1; fi
+        fi
+    fi
+  done
+fi
 
-void HighlightOverlayManager::SetOverlayMode(OverlayHighlightMode mode)
-{
-  mOverlayMode = mode;
-}
-
-OverlayHighlightMode HighlightOverlayManager::GetOverlayMode() const
-{
-  return mOverlayMode;
-}
-
-void HighlightOverlayManager::UpdateOverlay(Dali::Actor& activeHighlight)
-{
-  auto [sceneView, found] = FindParentSceneView(activeHighlight);
-  if(!sceneView || !found)
-  {
-    HideOverlay();
-    return;
-  }
-
-  if(!mOverlayActor)
-  {
-    CreateOverlay(sceneView);
-  }
-
-  if(mOverlayActor)
-  {
-    UpdateOverlayPosition(sceneView, activeHighlight);
-  }
-}
-
-void HighlightOverlayManager::HideOverlay()
-{
-  if(mOverlayActor)
-  {
-    auto overlay = mOverlayActor.GetHandle();
-    if(overlay)
-    {
-      overlay.SetProperty(Actor::Property::VISIBLE, false);
-    }
-  }
-}
-
-std::tuple<Scene3D::SceneView, bool> HighlightOverlayManager::FindParentSceneView(Actor current)
-{
-  Scene3D::SceneView sceneView;
-  bool hasModel = false;
-
-  while(current)
-  {
-    sceneView = Scene3D::SceneView::DownCast(current);
-    if(sceneView)
-    {
-      hasModel = true;
-      break;
-    }
-    current = current.GetParent();
-  }
-  return {sceneView, hasModel};
-}
-
-void HighlightOverlayManager::CreateOverlay(Scene3D::SceneView sceneView)
-{
-  auto overlay = Actor::New();
-  overlay.SetProperty(Actor::Property::ANCHOR_POINT, AnchorPoint::TOP_LEFT);
-  overlay.SetProperty(Actor::Property::PARENT_ORIGIN, ParentOrigin::TOP_LEFT);
-  overlay.SetProperty(Actor::Property::VISIBLE, false);
-  overlay.SetProperty(Actor::Property::COLOR, Color::YELLOW);
-  overlay.SetProperty(Actor::Property::SIZE, Vector2(0.0f, 0.0f));
-
-  sceneView.AddOverlay(overlay);
-  mOverlayActor = overlay;
-}
-
-void HighlightOverlayManager::UpdateOverlayPosition(Scene3D::SceneView sceneView, Actor& highlight)
-{
-  if(!mOverlayActor)
-    return;
-
-  auto overlay = mOverlayActor.GetHandle();
-  if(!overlay)
-    return;
-
-  Rect<float> extents = GetOverlayExtents(sceneView, highlight, overlay);
-
-  overlay.SetProperty(Actor::Property::POSITION, Vector2(extents.x, extents.y));
-  overlay.SetProperty(Actor::Property::SIZE, Vector2(extents.width, extents.height));
-  overlay.SetProperty(Actor::Property::VISIBLE, true);
-}
-
-Rect<float> HighlightOverlayManager::GetOverlayExtents(Scene3D::SceneView sceneView, Actor& highlight, Actor& overlay)
-{
-  if(mOverlayMode == OverlayHighlightMode::Manual)
-  {
-    return {mManualPosition.x, mManualPosition.y, mManualSize.width, mManualSize.height};
-  }
-
-  Vector3 size    = highlight.GetCurrentProperty<Vector3>(Actor::Property::SIZE);
-  Vector3 world   = highlight.GetCurrentProperty<Vector3>(Actor::Property::WORLD_POSITION);
-  Vector3 screen  = sceneView.WorldToScreen(world);
-
-  return {screen.x, screen.y, size.width, size.height};
-}
-
-} // namespace Dali::Toolkit::DevelControl
+echo "Build succeeded"
+exit 0
